### PR TITLE
Document graphql so that it shows up in the browser

### PR DESCRIPTION
**Pull request by shimonacarvalho**
## Description

Found that documenting the models themselves with `help_text` as well as the graphene objects with `description` gets pulled out into the documentation. 

## Testing

1.  `poetry install` to install any new dependencies.
2.  `poetry shell` to activate the virtual environment (assuming you don't have direnv set up to automatically do this).
3.  `inv db.start` to start the database.
4.  `python manage.py migrate` to apply all model migrations to the database.
5.  `python manage.py runserver` to run the server.

Make sure you run all the tests (command: `pytest`), check the build (`inv build.tidy`), 
Check out the api at http://127.0.0.1:8000/graphql 

On the top right corner, click on the documentation link and then click on the query section. Check that the queries are documented and the IncidentType and PersonType fields are documented as well. 

## Checklists

This PR contains one or more of the following types of changes:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality) 
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): The frontend will also need to be updated (in a related PR)

### As the author:

- [x] Code follows general [Python best practices](https://github.com/trussworks/django-graphql-be/blob/main/docs/Python%20Best%20Practices.md). 
- [ ] Tests have been added/modified, and all pass.
- [ ] Docs have been updated as necessary.
- [x] Code has been reformatted and linted by `yapf`
- [x] Code is type-annotated and `mypy`-compliant. 
- [x] Model code has been updated, and:
   - [x] New migrations have been generated and committed to the repository. 
   - [x] Migrations can be successfully applied to an existing instance of the database. They follow the principles of "no-downtime" migrations.

### As the reviewer:

- [x] I have read the docs and found that they answer my questions.
- [x] I have tested manually with input that has not been provided by the PR author.
- [x] I understand why these changes were made.

### CODE REVIEW

**Comment by shimonacarvalho** [comment]
[Figure out how to document our graphql schema](https://trello.com/c/aHDGnjlS/16-figure-out-how-to-document-our-graphql-schema)

**Review by coalkettler — APPROVED** [review]
Wow, I love this. It's super cool that GraphQL ships with API explorer-style documentation and I'm glad we're using it. Works great for me!

**Review by sandy-wright — APPROVED** [review]
Looks great! I checked, and it also supports markdown in these descriptions! You need to use explicit newline characters, but that's not a huge deal. This string:

```python
"Returns a **Hello World!** string."
"\n\n"
"Here again.\n"
"- what\n"
"- about\n"
"- this?\n"
```

looked like this in the schema:

Screen Shot 2022-03-23 at 2 40 23 PM

Super cool!!

**Comment by shimonacarvalho** [comment]
> Looks great! I checked, and it also supports markdown in these descriptions! You need to use explicit newline characters, but that's not a huge deal. This string:
> 
> ```python
> "Returns a **Hello World!** string."
> "\n\n"
> "Here again.\n"
> "- what\n"
> "- about\n"
> "- this?\n"
> ```
> 
> looked like this in the schema:
> 
> Screen Shot 2022-03-23 at 2 40 23 PM
> 
> Super cool!!

Wow pretty cool!

**Pull request merged**
